### ISSUE TITLE
Add a alert when the scheduler in set to "* * * * *"

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#209]
As a user, I want to have a warning message that says. : "

"You are about to run your scheduler every minute of every day, are you sure you want to continue?"
Button => YES / NO

https://www.javatpoint.com/python-tkinter-button

**Comment by Dr0p42** [comment]
Hello guys, I think it won't be possible to use Tkinter to  display a popin. We might consider looking for a solution like this one  maybe? https://www.stefaanlippens.net/jupyter-notebook-dialog.html

**Comment by Dr0p42** [comment]
Maybe something like that could be a first easy version:

```python
from IPython.display import display, Javascript
display(Javascript("""
alert('Warning you just scheduled a notebook to run every minute!');
"""))
```

Later on it could be nice to see if we can use `confirm` instead of `alert` to have the possibility to cancel if needed.

---

It's showing up like that on Firefox:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/22365519/131650401-e11ca93f-653c-4d4d-a458-b781762a9aa1.png">

**Comment by jravenel** [comment]
This task has been transformed to an alert as per as our discussion to lower impacts on the core feature.
