### ISSUE TITLE
Refactoring page hub

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#218]
Delete the 4 custom boxes + center the element when loading

**Comment by tparente-ui** [comment]
Hello @jravenel 

I've been working on this issue today, the file to modify was found in the authentificator repository, the path is as follows: `authentificator/naasauthentificator/home.py`
The 4 boxes have been removed from the delete_custom_boxes branch.
Otherwise I did not understand what had to be re-denter in addition to the remove of these boxes.

**Comment by FlorentLvr** [comment]
![image](https://user-images.githubusercontent.com/48032461/131968114-98734ed0-f808-4ac7-8cef-5b9e5f0e46f6.png)

**Comment by tparente-ui** [comment]
Hi !

Link of the PR : https://github.com/jupyter-naas/authenticator/pull/12

(Can't link the PR to the issue because this last is not link to the good repo)
