### ISSUE TITLE
Enable Jupyter-Dash inline display to enhance the dashboard building experience

### ISSUE THREAD

**Issue by jravenel** [jupyter-naas/naas#333]
It would give a better developper experience.

**Comment by jravenel** [comment]
Might have to create awesome-notebooks in the end @Dr0p42

**Comment by Dr0p42** [comment]
# Setup and usage of jupyter-dash

The goal is to have Dash working inline in Jupyterlab instead of having to start the app and open a new tab to see what's going on.

There is a library named `jupyter-dash` that is supposed to do just that.

The result should look like this:

![](https://user-images.githubusercontent.com/15064365/82324108-150d4200-99a7-11ea-8d22-5c1bb8acaadb.gif)


By going on the [repository](https://github.com/plotly/jupyter-dash) we can see that to install `jupyter-dash` we hust have to run `pip install jupyter-dash` but as we are on naas we have to run `pip install --user jupyter-dash` instead to have the installation being persistent between restarts.


It seems that we need to re build Jupyterlab to have everything working, so this means that we need to deploy a new release of naas embedding this Jupyterlab extension directly as users won't be able to do it themselves. (Only locally but it's not sufficient of course).

## Updating Dockerfile.dev

First test to do is to update the `.docker/dev/Dockerfile.dev` in `naas` repo and run a `make build` then `make run`.

<img width="509" alt="2022-08-09-15-33-13" src="https://user-images.githubusercontent.com/22365519/183689565-98f43f5b-c65f-4870-b6b1-691400306e06.png">

This line is here to install `jupyter-dash` and re build jupyter lab.

<img width="1872" alt="2022-08-09-15-34-33" src="https://user-images.githubusercontent.com/22365519/183689636-0959085b-7e22-43e3-98c8-00c4cb6a3def.png">

<img width="530" alt="2022-08-09-15-36-25" src="https://user-images.githubusercontent.com/22365519/183689641-105629a5-ea1c-45ce-8bc2-a8b7cb3dea9e.png">


Ok so it seems like we have a newly built container 👍

Let's try it now

## Running naas

`make run`

<img width="940" alt="2022-08-09-15-38-04" src="https://user-images.githubusercontent.com/22365519/183689683-6ac14a8f-84b2-4c9d-b758-8fef747ea3b8.png">


The app seems to be ready. Let's head to http://127.0.0.1:8888?token=naas

## Testing jupyter-dash

In jupyter-dash's Github repo we can see that there is an example notebook here:

https://github.com/plotly/jupyter-dash/blob/master/notebooks/getting_started.ipynb

We will download it and run it.

The notebook is using port `8050` as we are running naas in Docker (at least I am), then we need to update the `docker-compose.yaml` and restart the container.

<img width="290" alt="2022-08-09-15-45-37" src="https://user-images.githubusercontent.com/22365519/183689717-33e3dd10-a266-4666-aea8-776837c4f114.png">


Ok so after looking at the notebook it seems that `jupyter-dash` lab extension is just to allow jupyter-dash to open a new tab when running the `run_server` function.

It's not what we want right now. So I am following the testing on app.naas.ai instead.

## Debugging

I have some errors when running the `run_server`, everytime it is trying to load the app from `127.0.0.1:8050` which is not possible.

Not much luck by looking at the documentation. But I remember that we have a notebook about Dash in awesome-notebook that I already worked on [here](https://github.com/jupyter-naas/awesome-notebooks/blob/master/Dash/Dash_Deploy_app_in_Naas.ipynb).

We can see that we have this cell to configure the Flask/Dash app

<img width="906" alt="2022-08-09-17-06-32" src="https://user-images.githubusercontent.com/22365519/183689773-ed08fd73-c816-41d4-8801-b8827122a92d.png">

and we also have this `proxy` argument

<img width="795" alt="2022-08-09-17-06-51" src="https://user-images.githubusercontent.com/22365519/183689803-276a6669-8e35-4850-b06a-549894d7c001.png">

So after updating this line in the example notebook

<img width="1210" alt="2022-08-09-17-08-10" src="https://user-images.githubusercontent.com/22365519/183689839-095801ea-f8eb-4297-8683-a57f1b21e6e4.png">

and adding the proxy

<img width="1527" alt="2022-08-09-17-08-22" src="https://user-images.githubusercontent.com/22365519/183689875-0f892fd9-87b5-46b5-ba82-335466befbef.png">

we can see that I still have the same error.

But by looking at the network console we can see that the `requests_pathname_prefix` is useful

<img width="827" alt="2022-08-09-17-09-17" src="https://user-images.githubusercontent.com/22365519/183689920-74ac8121-634e-4458-b87a-0f0419f37b9a.png">


So what we want to acheive is to let know the app that we are running on `app.naas.ai` and not `127.0.0.1:8050`

After searching for a while, not much luck on the documentation, so I decided to look at the code of `jupyter-dash` and I saw [this](https://github.com/plotly/jupyter-dash/blob/master/jupyter_dash/jupyter_app.py#L35):

<img width="907" alt="2022-08-09-17-10-52" src="https://user-images.githubusercontent.com/22365519/183689950-b5b6dd84-27b0-428b-acfa-7c9c2e477aad.png">


So I tried to give it a shot.

<img width="1470" alt="2022-08-09-17-11-21" src="https://user-images.githubusercontent.com/22365519/183689979-d83743d2-dd84-4288-9568-7c3ea8c18d40.png">

<img width="1534" alt="2022-08-09-17-11-44" src="https://user-images.githubusercontent.com/22365519/183689983-3f6add49-da21-4b66-a31d-7b400afec14d.png">

And Voila! 

But I was wondering if the `proxy` parameter was still needed as Dash now knows that we are using `app.naas.ai`, so I removed it to see if I have a difference

<img width="1528" alt="2022-08-09-17-12-54" src="https://user-images.githubusercontent.com/22365519/183690020-132b1828-40ac-442f-aee2-178e070c361b.png">

And it's still working so that's good.

As I am using the variable `DASH_PORT` in `requests_pathname_prefix` I also decided to pass it to the `app.run_server` to be consistent.

<img width="1533" alt="2022-08-09-17-14-29" src="https://user-images.githubusercontent.com/22365519/183690033-559061ee-b671-445d-8234-59cf7ad49b3c.png">

Still working fine so I am happy with this.

## Conclusion

So the only thing needed to run `jupyter-dash` on naass is to;
- Run `pip install --user jupyter-dash`
- Create a `DASH_PORT = 8050` variable.
- Instantiate JupyterDash like so 
    ```
    app = JupyterDash(__name__,  server_url="https://app.naas.ai" ,external_stylesheets=external_stylesheets, requests_pathname_prefix=f'/user/{os.environ.get("JUPYTERHUB_USER")}/proxy/{DASH_PORT}/')
    ```
- Call `app.run_server(mode="inline", port=DASH_PORT)` like so.


And you should be good 👍

**Comment by jravenel** [comment]
cc @Dr0p42 we just discussed this issue and would like to do a working session with you to understand the testing locally of this. 

maybe with Ismail and Muhammed. Let's find time this week?

**Comment by jravenel** [comment]
This Issue is closed by PR on awesome-notebooks repo : https://github.com/jupyter-naas/awesome-notebooks/pull/1143
